apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-portfolio
  name: k8s-portfolio-deployment
  labels:
    app: k8s-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-portfolio
  template:
    metadata:
      labels:
        app: k8s-portfolio
    spec:
      containers:
      - name: k8s-portfolio
        image: {{ .Values.image }}
        imagePullPolicy: Always
