apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-portfolio
  name: k8s-portfolio-deployment
  labels:
    app: k8s-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-portfolio
  template:
    metadata:
      labels:
        app: k8s-portfolio
    spec:
      containers:
      - name: k8s-portfolio
        image: {{ .Values.image }}
        imagePullPolicy: Always
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.config
            subPath: nginx.config
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumes:
          - name: nginx-config
            configMap:
              name: nginx-custom-config
