apiVersion: v1
kind: Service
metadata:
  name: k8s-portfolio
spec:
  selector:
    app: k8s-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to NodePort if you don't have a LoadBalancer
