name: Docker Image CI - k8s_portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: Installing buildx to create image arm64
      run: docker buildx create --use

    - name: Build the Docker image and push to repo
      run: docker buildx build . --file Dockerfile --platform linux/arm64 --tag ${{ secrets.DOCKER_HUB_USERNAME }}/k8s_portfolio:1 --push
