name: Docker Image CI - k8s_portfolio

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'k8s_portfolio/k8s-portfolio-chart/values.yaml'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      #IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s_portfolio
      TAG: ${{ github.run_number }}
      #VALUES_FILE: k8s-portfolio-chart/values.yaml
    
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - uses: actions/checkout@v4

    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Write run number to values.yaml
      run: |
        yq -i '.image = "andresl123/k8s_portfolio:" + strenv(TAG)' k8s_portfolio/k8s-portfolio-chart/values.yaml

    - name: Installing buildx to create image arm64
      run: docker buildx create --use

    - name: Build the Docker image and push to repo
      run: docker buildx build . --file Dockerfile --platform linux/arm64 --tag ${{ secrets.DOCKER_HUB_USERNAME }}/k8s_portfolio:${{ github.run_number }} --push

    - name: Commit & push updated values.yaml
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${VALUES_FILE}"
        git commit -m "[skip ci] ci: bump image to $IMAGE:$TAG"
        git push
